require_relative 'validation'
require_relative 'accessors'
require_relative 'instance_counter'
require_relative 'company'
require_relative 'station'
require_relative 'route'
require_relative 'wagon'
require_relative 'wagon_cargo'
require_relative 'wagon_passen'
require_relative 'train'
require_relative 'train_cargo'
require_relative 'train_passen'
require_relative 'rail_road'
puts 'To create new RailRoad enter name_of_RailRoad = RailRoad.new'
puts 'like rr1 = RailRoad.new'
puts 'To view info about RailRoad and do some operations enter name_of_RailRoad.info'
puts 'for example rr1.info'